[project]
name = "metal2f0"
version = "1.0.0"
description = "Converts BaseColor + Metallic textures to Diffuse Albedo + F0 / Specular textures"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Tobias Wink", email = "sainth@sainth.de" }
]
requires-python = ">=3.14,<3.15"
dependencies = [
    "numpy",
    "openimageio",
    "pyside6",
]

[project.scripts]
metal2f0 = "metal2f0.app:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.21.0",
    "pytest>=9.1.1",
]
