[project]
name = "metal2fo"
version = "0.1.0"
description = "Converts BaseColor + Metallic textures to Diffuse Albedo + F0 / Specular textures"
readme = "README.md"
authors = [
    { name = "Tobias Wink", email = "sainth@sainth.de" }
]
requires-python = ">=3.14,<3.15"
dependencies = [
    "openimageio",
    "pyside6",
]

[project.scripts]
metal2fo = "metal2fo.app:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
